version: "3.9"

services:
  # ---------- MySQL database ----------
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    volumes:
      # Persist database
      - mysql_data:/var/lib/mysql
      # Run your SQL file to initialize users table
      - ./auth-service/sql:/docker-entrypoint-initdb.d:ro

  # ---------- Auth service ----------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      PORT: 3000
      JWT_SECRET: change_me_in_env
      JWT_TTL_MINUTES: 20
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: authdb
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    restart: always

volumes:
  mysql_data:
